spring.application.name=CLASES

# CONFIGURACION HIBRIDA DE BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/evaluacion_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345678}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACION DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SEGURIDAD Y GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=142480039149-6o8b59ulgbg07h2nm8gm1alqq0phj0ui.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# LOGGING Y SERVIDOR
logging.level.org.springframework.security=DEBUG
logging.level.root=ERROR
logging.level.org.springframework.web=DEBUG

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.port=${PORT:8080}
server.address=0.0.0.0